(in-package :vkvk)

;;basic type
(defctype vk-bool-32 :uint32)
(defctype vk-flags :uint32)


(defctype vk-handle :pointer)
#.(if (= 8 (foreign-type-size :pointer))
      `(defctype vk-non-dispatch-handle :pointer)
      `(defctype vk-non-dispatch-handle :uint64))

#.(if (= 8 (foreign-type-size :pointer))
      `(defctype size-t :uint64)
      `(defctype size-t :uint32))


(defctype vk-instance vk-handle)
(defctype vk-physical-device vk-handle)
(defctype vk-device vk-handle)
(defctype vk-queue vk-handle)
(defctype vk-command-buffer vk-handle)

(defctype vk-command-pool vk-non-dispatch-handle)
(defctype vk-fence vk-non-dispatch-handle)
(defctype vk-semaphore vk-non-dispatch-handle)
(defctype vk-event vk-non-dispatch-handle)
(defctype vk-render-pass vk-non-dispatch-handle)
(defctype vk-framebuffer vk-non-dispatch-handle)
(defctype vk-shader-module vk-non-dispatch-handle)
(defctype vk-validation-cache-ext vk-non-dispatch-handle)
(defctype vk-pipeline vk-non-dispatch-handle)
(defctype vk-pipeline-cache vk-non-dispatch-handle)
(defctype vk-device-memory vk-non-dispatch-handle)
(defctype vk-buffer vk-non-dispatch-handle)
(defctype vk-buffer-view vk-non-dispatch-handle)
(defctype vk-image vk-non-dispatch-handle)
(defctype vk-image-view vk-non-dispatch-handle)
(defctype vk-acceleration-structure-khr vk-non-dispatch-handle)
(defctype vk-sampler vk-non-dispatch-handle)
(defctype vk-sampler-ycbcr-conversion vk-non-dispatch-handle)
(defctype vk-descriptor-set-layout vk-non-dispatch-handle)
(defctype vk-pipeline-layout vk-non-dispatch-handle)
(defctype vk-descriptor-pool vk-non-dispatch-handle)
(defctype vk-descriptor-set vk-non-dispatch-handle)
(defctype vk-descriptor-update-template vk-non-dispatch-handle)
(defctype vk-query-pool vk-non-dispatch-handle)
(defctype vk-performance-configuration-intel vk-non-dispatch-handle)
(defctype vk-indirect-commands-layout-nv vk-non-dispatch-handle)
(defctype vk-surface-khr vk-non-dispatch-handle)
(defctype vk-display-khr vk-non-dispatch-handle)
(defctype vk-display-mode-khr vk-non-dispatch-handle)
(defctype vk-swapchain-khr vk-non-dispatch-handle)
(defctype vk-deferred-operation-khr vk-non-dispatch-handle)
(defctype vk-private-date-slot-ext vk-non-dispatch-handle)
(defctype vk-debug-utils-messenger-ext vk-non-dispatch-handle)
(defctype vk-debug-report-callback-ext vk-non-dispatch-handle)
(defctype vk-descriptor-set vk-non-dispatch-handle)

(defctype vk-device-size :uint64)
(defctype vk-device-address :uint64)
(defctype vk-sample-mask :uint32)

(defctype vk-void-function :pointer)
(defctype vk-allocation-function :pointer)
(defctype vk-reallocation-function :pointer)
(defctype vk-free-function :pointer)
(defctype vk-internal-allocation-notification :pointer)
(defctype vk-internal-free-notification :pointer)
(defctype pfn-vk-debug-utils-messenger-callback-ext :pointer)
(defctype pfn-vk-debug-report-callback-ext :pointer)

(defctype android-window :void)
(defcstruct wl-display) ;;unknow ~.~
(defcstruct wl-surface) ;;unknow ~.~
(defctype hinstance (:pointer :void))
(defctype hwnd (:pointer :void))
(defctype xcb-connection :void)
(defctype xcb-window :uint32)
(defctype xlib-display :void)
(defctype xlib-window :ulong)
(defctype idirect-fb :void) ;;unknow
(defctype idirect-fb-surface :void) ;;unknow
(defctype zx-handle :uint32) ;;unknow
(defctype gpp-stream-descriptor :uint32)
(defctype ca-metal-layer :void) ;;unknow

(defctype vk-instance-create-flags vk-flags)
(defctype vk-device-create-flags vk-flags)
(defctype vk-device-queue-create-flags vk-flags)
(defctype vk-fence-create-flags vk-flags)
(defctype vk-command-pool-create-flags vk-flags)
(defctype vk-semaphore-create-flags vk-flags)
(defctype vk-event-create-flags vk-flags)
(defctype vk-render-pass-create-flags vk-flags)
(defctype vk-framebuffer-create-flags vk-flags)
(defctype vk-image-create-flags vk-flags)
(defctype vk-module-create-flags vk-flags)
(defctype vk-validation-cache-create-flags-ext vk-flags)
(defctype vk-pipeline-create-flags vk-flags)
(defctype vk-pipeline-shader-stage-create-flags vk-flags)
(defctype vk-pipeline-vertex-input-state-create-flags vk-flags)
(defctype vk-pipeline-input-assembly-state-create-flags vk-flags)
(defctype vk-pipeline-tessellation-state-create-flags vk-flags)
(defctype vk-pipeline-viewport-state-create-flags vk-flags)
(defctype vk-pipeline-rasterization-state-create-flags vk-flags)
(defctype vk-pipeline-multisample-state-create-flags vk-flags)
(defctype vk-pipeline-depth-stencil-state-create-flags vk-flags)
(defctype vk-pipeline-color-blend-state-create-flags vk-flags)
(defctype vk-pipeline-dynamic-state-create-flags vk-flags)
(defctype vk-pipeline-cache-create-flags vk-flags)
(defctype vk-buffer-create-flags vk-flags)
(defctype vk-buffer-view-create-flags vk-flags)
(defctype vk-image-view-create-flags vk-flags)
(defctype vk-sampler-create-flags vk-flags)
(defctype vk-descriptor-set-layout-create-flags vk-flags)
(defctype vk-pipeline-layout-create-flags vk-flags)
(defctype vk-descriptor-pool-create-flags vk-flags)
(defctype vk-descriptor-update-template-create-flags vk-flags)
(defctype vk-query-pool-create-flags vk-flags)
(defctype vk-pipeline-viewport-swizzle-state-create-flags-nv vk-flags)
(defctype vk-pipeline-rasterization-conservative-state-create-flags-ext vk-flags)
(defctype vk-pipeline-discard-rectangle-state-create-flags-ext vk-flags)
(defctype vk-pipeline-coverage-to-color-state-create-flags-nv vk-flags)
(defctype vk-pipeline-coverage-reduction-state-create-flags-nv vk-flags)
(defctype vk-display-mode-create-flags-khr vk-flags)
(defctype vk-display-surface-create-flags-khr vk-flags)
(defctype vk-headless-surface-create-flags-ext vk-flags)
(defctype vk-swapchain-create-flags vk-flags)
(defctype vk-private-data-slot-create-flags-ext vk-flags)

(defctype vk-sample-count-flags vk-flags)
(defctype vk-reslove-mode-flags vk-flags)
(defctype vk-queue-flags vk-flags)
(defctype vk-pipeline-stage-flags vk-flags)
(defctype vk-performance-counter-description-flags-khr vk-flags)
(defctype vk-device-diagnostics-config-flags-nv vk-flags)
(defctype vk-command-buffer-usage-flags vk-flags)
(defctype vk-query-control-flags vk-flags)
(defctype vk-query-pipeline-statistic-flags vk-flags)
(defctype vk-external-fence-handle-type-flags vk-flags)
(defctype vk-fence-import-flags vk-flags)
(defctype vk-external-semaphore-handle-type-flags vk-flags)
(defctype vk-semaphore-wait-flags vk-flags)
(defctype vk-semaphore-import-flags vk-flags)
(defctype vk-access-flags vk-flags)
(defctype vk-image-aspect-flags vk-flags)
(defctype vk-attachment-description-flags vk-flags)
(defctype vk-subpass-description-flags vk-flags)
(defctype vk-pipeline-stage-flags vk-flags)
(defctype vk-dependency-flags vk-flags)
(defctype vk-image-usage-flags vk-flags)
(defctype vk-cull-mode-flags vk-flags)
(defctype vk-color-component-flags vk-flags)
(defctype vk-shader-stage-flags vk-flags)
(defctype vk-shader-stage-flags vk-flags)
(defctype vk-pipeline-compiler-control-flags-amd vk-flags)
(defctype vk-pipeline-creation-feedback-flags-ext vk-flags)
(defctype vk-memory-property-flags vk-flags)
(defctype vk-memory-heap-flags vk-flags)
(defctype vk-external-memory-handle-type-flags vk-flags)
(defctype vk-external-memory-handle-type-flags-nv vk-flags)
(defctype vk-memory-allocate-flags vk-flags)
(defctype vk-buffer-usage-flags vk-flags)
(defctype vk-image-aspect-flags Vk-flags)
(defctype vk-build-acceleration-structure-flags-nv vk-flags)
(defctype vk-geometry-flags-khr vk-flags)
(defctype vk-build-acceleration-structure-flags-khr vk-flags)
(defctype vk-descriptor-binding-flags vk-flags)
(defctype vk-acquire-profiling-lock-flags-khr vk-flags)
(defctype vk-conditional-rendering-flags-ext vk-flags)
(defctype vk-pipeline-rasterization-depth-clip-state-create-flags-ext vk-flags)
(defctype vk-pipeline-rasterization-state-stream-create-flags-ext vk-flags)
(defctype vk-sample-count-flags vk-flags)
(defctype vk-pipeline-coverage-modulation-state-create-flags-nv vk-flags)
(defctype vk-indirect-commands-layout-usage-flags-nv vk-flags)
(defctype vk-indirect-state-flags-nv vk-flags)
(defctype vk-sparse-image-format-flags vk-flags)
(defctype vk-sparse-memory-bind-flags vk-flags)
(defctype vk-surface-transform-flags-khr vk-flags)
(defctype vk-display-plane-alpha-flags-khr vk-flags)
(defctype vk-composite-alpha-flags-khr vk-flags)
(defctype vk-surface-counter-flags-ext vk-flags)
(defctype vk-device-group-present-mode-flags-khr vk-flags)
(defctype vk-build-acceleration-structure-flags-khr vk-flags)
(defctype vk-geometry-instance-flags-khr vk-flags)
(defctype vk-subgroup-feature-flags vk-flags)
(defctype vk-shader-core-properties-flags-amd vk-flags)
(defctype vk-format-feature-flags vk-flags)
(defctype vk-external-memory-handle-type-flags-nv vk-flags)
(defctype vk-external-memory-feature-flags-nv vk-flags)
(defctype vk-external-memory-feature-flags vk-flags)
(defctype vk-external-memory-handle-type-flags vk-flags)
(defctype vk-external-semaphore-handle-type-flags vk-flags)
(defctype vk-external-semaphore-feature-flags vk-flags)
(defctype vk-external-fence-feature-flags vk-flags)
(defctype vk-debug-utils-messenger-create-flags-ext vk-flags)
(defctype vk-debug-utils-message-severity-flags-ext vk-flags)
(defctype vk-debug-utils-message-type-flags-ext vk-flags)
(defctype vk-debug-utils-messenger-callback-data-flags-ext vk-flags)
(defctype vk-debug-report-flags-ext vk-flags)
(defctype vk-tool-purpose-flags-ext vk-flags)
(defctype vk-memory-map-flags vk-flags)
(defctype vk-query-result-flags vk-flags)
(defctype vk-descriptor-pool-reset-flags vk-flags)
(defctype vk-command-pool-reset-flags vk-flags)
(defctype vk-command-buffer-reset-flags vk-flags)
(defctype vk-stencil-face-flags vk-flags)
(defctype vk-command-pool-trim-flags vk-flags)
(defctype vk-peer-memory-feature-flags vk-flags)

(defun check-foreign-enum-type (type val)
  (member val (foreign-enum-keyword-list type)))

(deftype foreign-enum-type (type)
  (let ((check (gensym)))
    (setf (symbol-function check)
	  #'(lambda (val)
	      (check-foreign-enum-type type val)))
    `(satisfies ,check)))

(defun check-struct-type (val)
  `(typep ,val (foreign-type vkstructuretype)))
(deftype vk-struct-type ()
  `(satisfies check-struct-type))

(defun check-result (val)
  (if (and `(typep ,val (foreign-type VkResult))
	   (eql val :SUCCESS))
      t
      (error "error: ~a~%" val)))
(deftype vk-result ()
  `(satisfies check-result))

(defun check-validation-check (val)
  `(typep ,val (foreign-type VkValidationCheckEXT)))
(deftype vk-validation-check ()
  `(satisfies check-validation-check))

(defun check-validation-feature-enable-ext (val)
  `(typep ,val (foreign-type VkValidationFeatureEnableEXT)))
(deftype vk-validation-feature-enable-ext ()
  `(satisfies check-validation-feature-enable-ext))

(defun check-validation-feature-disable-ext (val)
  `(typep ,val (foreign-type VkValidationFeatureDisableEXT)))
(deftype vk-validation-feature-disable-ext ()
  `(satisfies check-validation-feature-disable-ext))

(defun check-vendor-id (val)
  `(typep ,val (foreign-type VkVendorId)))
(deftype vk-vendor-id ()
  `(satisfies check-vend-id))

(defun check-physical-device-type (val)
    `(typep ,val (foreign-type VkPhysicalDeviceType)))
(deftype vk-physical-device-type ()
  `(satisfies check-physical-device-type))

(defun check-driver-id (val)
  `(typep ,val (foreign-type VkDriverId)))
(deftype vk-driver-id ()
  `(satisfies check-driver-id))

(defun check-queue-flag-bits (val)
  `(typep ,val (foreign-type VkQueueFlagBits)))
(deftype vk-queue-flag-bits ()
  `(satisfies check-queue-flag-bits))

(defun check-performance-counter-unit-khr (val)
  `(typep ,val (foreign-type VkPerformanceCounterUnitKHR)))
(deftype vk-performance-counter-unit-khr ()
  `(satisfies check-performance-counter-unit-khr))
 
(defun check-performance-counter-scope-khr (val)
  `(typep ,val (foreign-type VkPerformanceCounterScopeKHR)))
(deftype vk-performance-counter-scope-khr ()
  `(satisfies check-performance-counter-scope-khr))
 
(defun check-performance-counter-storage-khr (val)
  `(typep ,val (foreign-type VkPerformanceCounterStorageKHR)))
(deftype vk-performance-counter-storage-khr ()
  `(satisfies check-performance-counter-storage-khr))
 
(defun check-performance-counter-description-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkPerformanceCounterDescriptionFlagBitsKHR)))
(deftype vk-performance-counter-description-flag-bits-khr ()
  `(satisfies check-performance-counter-description-flag-bits-khr))
 
(defun check-memory-overallocation-behavior-amd (val)
  `(typep ,val (foreign-enum-type VkMemoryOverallocationBehaviorAMD)))
(deftype vk-memory-overallocation-behavior-amd ()
  `(satisfies check-memory-overallocation-behavior-amd))
 
(defun check-device-diagnostics-config-flag-bits-nv (val)
  `(typep ,val (foreign-enum-type VkDeviceDiagnosticsConfigFlagBitsNV)))
(deftype vk-device-diagnostics-config-flag-bits-nv ()
  `(satisfies check-device-diagnostics-config-flag-bits-nv))
 
(defun check-device-queue-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkDeviceQueueCreateFlagBits)))
(deftype vk-device-queue-create-flag-bits ()
  `(satisfies check-device-queue-create-flag-bits))
 
(defun check-queue-global-priority-ext (val)
  `(typep ,val (foreign-enum-type VkQueueGlobalPriorityEXT)))
(deftype vk-queue-global-priority-ext ()
  `(satisfies check-queue-global-priority-ext))
 
(defun check-command-pool-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkCommandPoolCreateFlagBits)))
(deftype vk-command-pool-create-flag-bits ()
  `(satisfies check-command-pool-create-flag-bits))
 
(defun check-command-pool-reset-flag-bits (val)
  `(typep ,val (foreign-enum-type VkCommandPoolResetFlagBits)))
(deftype vk-command-pool-reset-flag-bits ()
  `(satisfies check-command-pool-reset-flag-bits))
 
(defun check-command-buffer-level (val)
  `(typep ,val (foreign-enum-type VkCommandBufferLevel)))
(deftype vk-command-buffer-level ()
  `(satisfies check-command-buffer-level))
 
(defun check-command-buffer-reset-flag-bits (val)
  `(typep ,val (foreign-enum-type VkCommandBufferResetFlagBits)))
(deftype vk-command-buffer-reset-flag-bits ()
  `(satisfies check-command-buffer-reset-flag-bits))
 
(defun check-command-buffer-usage-flag-bits (val)
  `(typep ,val (foreign-enum-type VkCommandBufferUsageFlagBits)))
(deftype vk-command-buffer-usage-flag-bits ()
  `(satisfies check-command-buffer-usage-flag-bits))
 
(defun check-pipeline-stage-flag-bits (val)
  `(typep ,val (foreign-enum-type VkPipelineStageFlagBits)))
(deftype vk-pipeline-stage-flag-bits ()
  `(satisfies check-pipeline-stage-flag-bits))
 
(defun check-access-flag-bits (val)
  `(typep ,val (foreign-enum-type VkAccessFlagBits)))
(deftype vk-access-flag-bits ()
  `(satisfies check-access-flag-bits))
 
(defun check-fence-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkFenceCreateFlagBits)))
(deftype vk-fence-create-flag-bits ()
  `(satisfies check-fence-create-flag-bits))
 
(defun check-device-event-type-ext (val)
  `(typep ,val (foreign-enum-type VkDeviceEventTypeEXT)))
(deftype vk-device-event-type-ext ()
  `(satisfies check-device-event-type-ext))
 
(defun check-display-event-type-ext (val)
  `(typep ,val (foreign-enum-type VkDisplayEventTypeEXT)))
(deftype vk-display-event-type-ext ()
  `(satisfies check-display-event-type-ext))
 
(defun check-fence-import-flag-bits (val)
  `(typep ,val (foreign-enum-type VkFenceImportFlagBits)))
(deftype vk-fence-import-flag-bits ()
  `(satisfies check-fence-import-flag-bits))
 
(defun check-semaphore-type (val)
  `(typep ,val (foreign-enum-type VkSemaphoreType)))
(deftype vk-semaphore-type ()
  `(satisfies check-semaphore-type))
 
(defun check-semaphore-wait-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSemaphoreWaitFlagBits)))
(deftype vk-semaphore-wait-flag-bits ()
  `(satisfies check-semaphore-wait-flag-bits))
 
(defun check-semaphore-import-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSemaphoreImportFlagBits)))
(deftype vk-semaphore-import-flag-bits ()
  `(satisfies check-semaphore-import-flag-bits))
 
(defun check-dependency-flag-bits (val)
  `(typep ,val (foreign-enum-type VkDependencyFlagBits)))
(deftype vk-dependency-flag-bits ()
  `(satisfies check-dependency-flag-bits))
 
(defun check-time-domain-ext (val)
  `(typep ,val (foreign-enum-type VkTimeDomainEXT)))
(deftype vk-time-domain-ext ()
  `(satisfies check-time-domain-ext))
 
(defun check-render-pass-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkRenderPassCreateFlagBits)))
(deftype vk-render-pass-create-flag-bits ()
  `(satisfies check-render-pass-create-flag-bits))
 
(defun check-attachment-description-flag-bits (val)
  `(typep ,val (foreign-enum-type VkAttachmentDescriptionFlagBits)))
(deftype vk-attachment-description-flag-bits ()
  `(satisfies check-attachment-description-flag-bits))
 
(defun check-attachment-load-op (val)
  `(typep ,val (foreign-enum-type VkAttachmentLoadOp)))
(deftype vk-attachment-load-op ()
  `(satisfies check-attachment-load-op))
 
(defun check-attachment-store-op (val)
  `(typep ,val (foreign-enum-type VkAttachmentStoreOp)))
(deftype vk-attachment-store-op ()
  `(satisfies check-attachment-store-op))
 
(defun check-subpass-description-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSubpassDescriptionFlagBits)))
(deftype vk-subpass-description-flag-bits ()
  `(satisfies check-subpass-description-flag-bits))
 
(defun check-resolve-mode-flag-bits (val)
  `(typep ,val (foreign-enum-type VkResolveModeFlagBits)))
(deftype vk-resolve-mode-flag-bits ()
  `(satisfies check-resolve-mode-flag-bits))
 
(defun check-framebuffer-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkFramebufferCreateFlagBits)))
(deftype vk-framebuffer-create-flag-bits ()
  `(satisfies check-framebuffer-create-flag-bits))
 
(defun check-subpass-contents (val)
  `(typep ,val (foreign-enum-type VkSubpassContents)))
(deftype vk-subpass-contents ()
  `(satisfies check-subpass-contents))
 
(defun check-scope-nv (val)
  `(typep ,val (foreign-enum-type VkScopeNV)))
(deftype vk-scope-nv ()
  `(satisfies check-scope-nv))
 
(defun check-component-type-nv (val)
  `(typep ,val (foreign-enum-type VkComponentTypeNV)))
(deftype vk-component-type-nv ()
  `(satisfies check-component-type-nv))
 
(defun check-validation-cache-header-version-ext (val)
  `(typep ,val (foreign-enum-type VkValidationCacheHeaderVersionEXT)))
(deftype vk-validation-cache-header-version-ext ()
  `(satisfies check-validation-cache-header-version-ext))
 
(defun check-pipeline-shader-stage-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkPipelineShaderStageCreateFlagBits)))
(deftype vk-pipeline-shader-stage-create-flag-bits ()
  `(satisfies check-pipeline-shader-stage-create-flag-bits))
 
(defun check-shader-stage-flag-bits (val)
  `(typep ,val (foreign-enum-type VkShaderStageFlagBits)))
(deftype vk-shader-stage-flag-bits ()
  `(satisfies check-shader-stage-flag-bits))
 
(defun check-pipeline-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkPipelineCreateFlagBits)))
(deftype vk-pipeline-create-flag-bits ()
  `(satisfies check-pipeline-create-flag-bits))
 
(defun check-dynamic-state (val)
  `(typep ,val (foreign-enum-type VkDynamicState)))
(deftype vk-dynamic-state ()
  `(satisfies check-dynamic-state))
 
(defun check-pipeline-cache-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkPipelineCacheCreateFlagBits)))
(deftype vk-pipeline-cache-create-flag-bits ()
  `(satisfies check-pipeline-cache-create-flag-bits))
 
(defun check-pipeline-cache-header-version (val)
  `(typep ,val (foreign-enum-type VkPipelineCacheHeaderVersion)))
(deftype vk-pipeline-cache-header-version ()
  `(satisfies check-pipeline-cache-header-version))
 
(defun check-pipeline-bind-point (val)
  `(typep ,val (foreign-enum-type VkPipelineBindPoint)))
(deftype vk-pipeline-bind-point ()
  `(satisfies check-pipeline-bind-point))
 
(defun check-pipeline-executable-statistic-format-khr (val)
  `(typep ,val (foreign-enum-type VkPipelineExecutableStatisticFormatKHR)))
(deftype vk-pipeline-executable-statistic-format-khr ()
  `(satisfies check-pipeline-executable-statistic-format-khr))
 
(defun check-shader-info-type-amd (val)
  `(typep ,val (foreign-enum-type VkShaderInfoTypeAMD)))
(deftype vk-shader-info-type-amd ()
  `(satisfies check-shader-info-type-amd))
 
(defun check-ray-tracing-shader-group-type-khr (val)
  `(typep ,val (foreign-enum-type VkRayTracingShaderGroupTypeKHR)))
(deftype vk-ray-tracing-shader-group-type-khr ()
  `(satisfies check-ray-tracing-shader-group-type-khr))
 
(defun check-pipeline-creation-feedback-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkPipelineCreationFeedbackFlagBitsEXT)))
(deftype vk-pipeline-creation-feedback-flag-bits-ext ()
  `(satisfies check-pipeline-creation-feedback-flag-bits-ext))
 
(defun check-pipeline-creatioin-feedback-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkPipelineCreationFeedbackFlagBitsEXT)))
(deftype vk-pipeline-creatioin-feedback-flag-bits-ext ()
  `(satisfies check-pipeline-creatioin-feedback-flag-bits-ext))
 
(defun check-internal-allocation-type (val)
  `(typep ,val (foreign-enum-type VkInternalAllocationType)))
(deftype vk-internal-allocation-type ()
  `(satisfies check-internal-allocation-type))
 
(defun check-memory-heap-flag-bits (val)
  `(typep ,val (foreign-enum-type VkMemoryHeapFlagBits)))
(deftype vk-memory-heap-flag-bits ()
  `(satisfies check-memory-heap-flag-bits))
 
(defun check-memory-property-flag-bits (val)
  `(typep ,val (foreign-enum-type VkMemoryPropertyFlagBits)))
(deftype vk-memory-property-flag-bits ()
  `(satisfies check-memory-property-flag-bits))
 
(defun check-external-memory-handle-type-flag-bits-nv (val)
  `(typep ,val (foreign-enum-type VkExternalMemoryHandleTypeFlagBitsNV)))
(deftype vk-external-memory-handle-type-flag-bits-nv ()
  `(satisfies check-external-memory-handle-type-flag-bits-nv))
 
(defun check-memory-allocate-flag-bits (val)
  `(typep ,val (foreign-enum-type VkMemoryAllocateFlagBits)))
(deftype vk-memory-allocate-flag-bits ()
  `(satisfies check-memory-allocate-flag-bits))
 
(defun check-peer-memory-feature-flag-bits (val)
  `(typep ,val (foreign-enum-type VkPeerMemoryFeatureFlagBits)))
(deftype vk-peer-memory-feature-flag-bits ()
  `(satisfies check-peer-memory-feature-flag-bits))
 
(defun check-buffer-usage-flag-bits (val)
  `(typep ,val (foreign-enum-type VkBufferUsageFlagBits)))
(deftype vk-buffer-usage-flag-bits ()
  `(satisfies check-buffer-usage-flag-bits))
 
(defun check-buffer-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkBufferCreateFlagBits)))
(deftype vk-buffer-create-flag-bits ()
  `(satisfies check-buffer-create-flag-bits))
 
(defun check-image-usage-flag-bits (val)
  `(typep ,val (foreign-enum-type VkImageUsageFlagBits)))
(deftype vk-image-usage-flag-bits ()
  `(satisfies check-image-usage-flag-bits))
 
(defun check-image-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkImageCreateFlagBits)))
(deftype vk-image-create-flag-bits ()
  `(satisfies check-image-create-flag-bits))
 
(defun check-image-type (val)
  `(typep ,val (foreign-enum-type VkImageType)))
(deftype vk-image-type ()
  `(satisfies check-image-type))
 
(defun check-image-tiling (val)
  `(typep ,val (foreign-enum-type VkImageTiling)))
(deftype vk-image-tiling ()
  `(satisfies check-image-tiling))
 
(defun check-image-layout (val)
  `(typep ,val (foreign-enum-type VkImageLayout)))
(deftype vk-image-layout ()
  `(satisfies check-image-layout))
 
(defun check-image-view-type (val)
  `(typep ,val (foreign-enum-type VkImageViewType)))
(deftype vk-image-view-type ()
  `(satisfies check-image-view-type))
 
(defun check-image-view-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkImageViewCreateFlagBits)))
(deftype vk-image-view-create-flag-bits ()
  `(satisfies check-image-view-create-flag-bits))
 
(defun check-image-aspect-flag-bits (val)
  `(typep ,val (foreign-enum-type VkImageAspectFlagBits)))
(deftype vk-image-aspect-flag-bits ()
  `(satisfies check-image-aspect-flag-bits))
 
(defun check-component-swizzle (val)
  `(typep ,val (foreign-enum-type VkComponentSwizzle)))
(deftype vk-component-swizzle ()
  `(satisfies check-component-swizzle))
 
(defun check-sharing-mode (val)
  `(typep ,val (foreign-enum-type VkSharingMode)))
(deftype vk-sharing-mode ()
  `(satisfies check-sharing-mode))
 
(defun check-acceleration-structure-type-khr (val)
  `(typep ,val (foreign-enum-type VkAccelerationStructureTypeKHR)))
(deftype vk-acceleration-structure-type-khr ()
  `(satisfies check-acceleration-structure-type-khr))
 
(defun check-build-acceleration-structure-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkBuildAccelerationStructureFlagBitsKHR)))
(deftype vk-build-acceleration-structure-flag-bits-khr ()
  `(satisfies check-build-acceleration-structure-flag-bits-khr))
 
(defun check-geometry-type-khr (val)
  `(typep ,val (foreign-enum-type VkGeometryTypeKHR)))
(deftype vk-geometry-type-khr ()
  `(satisfies check-geometry-type-khr))
 
(defun check-geometry-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkGeometryFlagBitsKHR)))
(deftype vk-geometry-flag-bits-khr ()
  `(satisfies check-geometry-flag-bits-khr))
 
(defun check-acceleration-structure-memory-requirements-type-khr (val)
  `(typep ,val (foreign-enum-type VkAccelerationStructureMemoryRequirementsTypeKHR)))
(deftype vk-acceleration-structure-memory-requirements-type-khr ()
  `(satisfies check-acceleration-structure-memory-requirements-type-khr))
 
(defun check-acceleration-structure-build-type-khr (val)
  `(typep ,val (foreign-enum-type VkAccelerationStructureBuildTypeKHR)))
(deftype vk-acceleration-structure-build-type-khr ()
  `(satisfies check-acceleration-structure-build-type-khr))
 
(defun check-sampler-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSamplerCreateFlagBits)))
(deftype vk-sampler-create-flag-bits ()
  `(satisfies check-sampler-create-flag-bits))
 
(defun check-sampler-reduction-mode (val)
  `(typep ,val (foreign-enum-type VkSamplerReductionMode)))
(deftype vk-sampler-reduction-mode ()
  `(satisfies check-sampler-reduction-mode))
 
(defun check-filter (val)
  `(typep ,val (foreign-enum-type VkFilter)))
(deftype vk-filter ()
  `(satisfies check-filter))
 
(defun check-sampler-mipmap-mode (val)
  `(typep ,val (foreign-enum-type VkSamplerMipmapMode)))
(deftype vk-sampler-mipmap-mode ()
  `(satisfies check-sampler-mipmap-mode))
 
(defun check-sampler-address-mode (val)
  `(typep ,val (foreign-enum-type VkSamplerAddressMode)))
(deftype vk-sampler-address-mode ()
  `(satisfies check-sampler-address-mode))
 
(defun check-border-color (val)
  `(typep ,val (foreign-enum-type VkBorderColor)))
(deftype vk-border-color ()
  `(satisfies check-border-color))
 
(defun check-sampler-ycbcr-model-conversion (val)
  `(typep ,val (foreign-enum-type VkSamplerYcbcrModelConversion)))
(deftype vk-sampler-ycbcr-model-conversion ()
  `(satisfies check-sampler-ycbcr-model-conversion))
 
(defun check-sampler-ycbcr-range (val)
  `(typep ,val (foreign-enum-type VkSamplerYcbcrRange)))
(deftype vk-sampler-ycbcr-range ()
  `(satisfies check-sampler-ycbcr-range))
 
(defun check-chroma-location (val)
  `(typep ,val (foreign-enum-type VkChromaLocation)))
(deftype vk-chroma-location ()
  `(satisfies check-chroma-location))
 
(defun check-desriptor-set-layout-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkDescriptorSetLayoutCreateFlagBits)))
(deftype vk-desriptor-set-layout-create-flag-bits ()
  `(satisfies check-desriptor-set-layout-create-flag-bits))
 
(defun check-descriptor-binding-flag-bits (val)
  `(typep ,val (foreign-enum-type VkDescriptorBindingFlagBits)))
(deftype vk-descriptor-binding-flag-bits ()
  `(satisfies check-descriptor-binding-flag-bits))
 
(defun check-descriptor-pool-create-flag-bits (val)
  `(typep ,val (foreign-enum-type VkDescriptorPoolCreateFlagBits)))
(deftype vk-descriptor-pool-create-flag-bits ()
  `(satisfies check-descriptor-pool-create-flag-bits))
 
(defun check-descriptor-type  (val)
  `(typep ,val (foreign-enum-type VkDescriptorType)))
(deftype vk-descriptor-type ()
  `(satisfies check-descriptor-type))
 
(defun check-descriptor-update-template-type (val)
  `(typep ,val (foreign-enum-type VkDescriptorUpdateTemplateType)))
(deftype vk-descriptor-update-template-type ()
  `(satisfies check-descriptor-update-template-type))
 
(defun check-query-type (val)
  `(typep ,val (foreign-enum-type VkQueryType)))
(deftype vk-query-type ()
  `(satisfies check-query-type))
 
(defun check-query-control-flag-bits (val)
  `(typep ,val (foreign-enum-type VkQueryControlFlagBits)))
(deftype vk-query-control-flag-bits ()
  `(satisfies check-query-control-flag-bits))
 
(defun check-queyr-result-flag-bits (val)
  `(typep ,val (foreign-enum-type VkQueryResultFlagBits)))
(deftype vk-queyr-result-flag-bits ()
  `(satisfies check-queyr-result-flag-bits))
 
(defun check-query-pipeline-statistic-flag-bits (val)
  `(typep ,val (foreign-enum-type VkQueryPipelineStatisticFlagBits)))
(deftype vk-query-pipeline-statistic-flag-bits ()
  `(satisfies check-query-pipeline-statistic-flag-bits))
 
(defun check-performance-parameter-type-intel (val)
  `(typep ,val (foreign-enum-type VkPerformanceParameterTypeINTEL)))
(deftype vk-performance-parameter-type-intel ()
  `(satisfies check-performance-parameter-type-intel))
 
(defun check-performance-value-type-intel (val)
  `(typep ,val (foreign-enum-type VkPerformanceValueTypeINTEL)))
(deftype vk-performance-value-type-intel ()
  `(satisfies check-performance-value-type-intel))
 
(defun check-query-pool-sampling-mode-intel (val)
  `(typep ,val (foreign-enum-type VkQueryPoolSamplingModeINTEL)))
(deftype vk-query-pool-sampling-mode-intel ()
  `(satisfies check-query-pool-sampling-mode-intel))
 
(defun check-performance-override-type-intel (val)
  `(typep ,val (foreign-enum-type VkPerformanceOverrideTypeINTEL)))
(deftype vk-performance-override-type-intel ()
  `(satisfies check-performance-override-type-intel))
 
(defun check-performance-configuration-type-intel (val)
  `(typep ,val (foreign-enum-type VkPerformanceConfigurationTypeINTEL)))
(deftype vk-performance-configuration-type-intel ()
  `(satisfies check-performance-configuration-type-intel))
 
(defun check-primitive-topology (val)
  `(typep ,val (foreign-enum-type VkPrimitiveTopology)))
(deftype vk-primitive-topology ()
  `(satisfies check-primitive-topology))
 
(defun check-index-type (val)
  `(typep ,val (foreign-enum-type VkIndexType)))
(deftype vk-index-type ()
  `(satisfies check-index-type))
 
(defun check-conditional-rendering-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkConditionalRenderingFlagBitsEXT)))
(deftype vk-conditional-rendering-flag-bits-ext ()
  `(satisfies check-conditional-rendering-flag-bits-ext))
 
(defun check-vertex-input-rate (val)
  `(typep ,val (foreign-enum-type VkVertexInputRate)))
(deftype vk-vertex-input-rate ()
  `(satisfies check-vertex-input-rate))
 
(defun check-tessellation-domain-origin (val)
  `(typep ,val (foreign-enum-type VkTessellationDomainOrigin)))
(deftype vk-tessellation-domain-origin ()
  `(satisfies check-tessellation-domain-origin))
 
(defun check-viewport-coordinate-swizzle-nv (val)
  `(typep ,val (foreign-enum-type VkViewportCoordinateSwizzleNV)))
(deftype vk-viewport-coordinate-swizzle-nv ()
  `(satisfies check-viewport-coordinate-swizzle-nv))
 
(defun check-point-clipping-behavior (val)
  `(typep ,val (foreign-enum-type VkPointClippingBehavior)))
(deftype vk-point-clipping-behavior ()
  `(satisfies check-point-clipping-behavior))
 
(defun check-rasterization-order-amd (val)
  `(typep ,val (foreign-enum-type VkRasterizationOrderAMD)))
(deftype vk-rasterization-order-amd ()
  `(satisfies check-rasterization-order-amd))
 
(defun check-shading-rate-palette-entry-nv (val)
  `(typep ,val (foreign-enum-type VkShadingRatePaletteEntryNV)))
(deftype vk-shading-rate-palette-entry-nv ()
  `(satisfies check-shading-rate-palette-entry-nv))
 
(defun check-coarse-sample-order-type-nv (val)
  `(typep ,val (foreign-enum-type VkCoarseSampleOrderTypeNV)))
(deftype vk-coarse-sample-order-type-nv ()
  `(satisfies check-coarse-sample-order-type-nv))
 
(defun check-line-rasterization-mode-ext (val)
  `(typep ,val (foreign-enum-type VkLineRasterizationModeEXT)))
(deftype vk-line-rasterization-mode-ext ()
  `(satisfies check-line-rasterization-mode-ext))
 
(defun check-front-face (val)
  `(typep ,val (foreign-enum-type VkFrontFace)))
(deftype vk-front-face ()
  `(satisfies check-front-face))
 
(defun check-cull-mode-flag-bits (val)
  `(typep ,val (foreign-enum-type VkCullModeFlagBits)))
(deftype vk-cull-mode-flag-bits ()
  `(satisfies check-cull-mode-flag-bits))
 
(defun check-polygon-mode (val)
  `(typep ,val (foreign-enum-type VkPolygonMode)))
(deftype vk-polygon-mode ()
  `(satisfies check-polygon-mode))
 
(defun check-conservative-rasterization-mode-ext (val)
  `(typep ,val (foreign-enum-type VkConservativeRasterizationModeEXT)))
(deftype vk-conservative-rasterization-mode-ext ()
  `(satisfies check-conservative-rasterization-mode-ext))
 
(defun check-discard-rectangle-mode-ext (val)
  `(typep ,val (foreign-enum-type VkDiscardRectangleModeEXT)))
(deftype vk-discard-rectangle-mode-ext ()
  `(satisfies check-discard-rectangle-mode-ext))
 
(defun check-stencil-face-flag-bits (val)
  `(typep ,val (foreign-enum-type VkStencilFaceFlagBits)))
(deftype vk-stencil-face-flag-bits ()
  `(satisfies check-stencil-face-flag-bits))
 
(defun check-compare-op (val)
  `(typep ,val (foreign-enum-type VkCompareOp)))
(deftype vk-compare-op ()
  `(satisfies check-compare-op))
 
(defun check-stencil-op (val)
  `(typep ,val (foreign-enum-type VkStencilOp)))
(deftype vk-stencil-op ()
  `(satisfies check-stencil-op))
 
(defun check-coverage-reduction-mode-nv (val)
  `(typep ,val (foreign-enum-type VkCoverageReductionModeNV)))
(deftype vk-coverage-reduction-mode-nv ()
  `(satisfies check-coverage-reduction-mode-nv))
 
(defun check-coverage-modulation-mode-nv (val)
  `(typep ,val (foreign-enum-type VkCoverageModulationModeNV)))
(deftype vk-coverage-modulation-mode-nv ()
  `(satisfies check-coverage-modulation-mode-nv))
 
(defun check-blend-factor (val)
  `(typep ,val (foreign-enum-type VkBlendFactor)))
(deftype vk-blend-factor ()
  `(satisfies check-blend-factor))
 
(defun check-blend-op (val)
  `(typep ,val (foreign-enum-type VkBlendOp)))
(deftype vk-blend-op ()
  `(satisfies check-blend-op))
 
(defun check-blend-overlap-ext (val)
  `(typep ,val (foreign-enum-type) VkBlendOverlapEXT))
(deftype vk-blend-overlap-ext ()
  `(satisfies check-blend-overlap-ext))
 
(defun check-logic-op (val)
  `(typep ,val (foreign-enum-type VkLogicOp)))
(deftype vk-logic-op ()
  `(satisfies check-logic-op))
 
(defun check-color-component-flag-bits (val)
  `(typep ,val (foreign-enum-type VkColorComponentFlagBits)))
(deftype vk-color-component-flag-bits ()
  `(satisfies check-color-component-flag-bits))
 
(defun check-indirect-commands-layout-usage-flag-bits-nv (val)
  `(typep ,val (foreign-enum-type VkIndirectCommandsLayoutUsageFlagBitsNV)))
(deftype vk-indirect-commands-layout-usage-flag-bits-nv ()
  `(satisfies check-indirect-commands-layout-usage-flag-bits-nv))
 
(defun check-indirect-state-flag-bits-nv (val)
  `(typep ,val (foreign-enum-type VkIndirectStateFlagBitsNV)))
(deftype vk-indirect-state-flag-bits-nv ()
  `(satisfies check-indirect-state-flag-bits-nv))
 
(defun check-indirect-commands-token-type-nv (val)
  `(typep ,val (foreign-enum-type VkIndirectCommandsTokenTypeNV)))
(deftype vk-indirect-commands-token-type-nv ()
  `(satisfies check-indirect-commands-token-type-nv))
 
(defun check-sparse-image-format-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSparseImageFormatFlagBits)))
(deftype vk-sparse-image-format-flag-bits ()
  `(satisfies check-sparse-image-format-flag-bits))
 
(defun check-sparse-memory-bind-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSparseMemoryBindFlagBits)))
(deftype vk-sparse-memory-bind-flag-bits ()
  `(satisfies check-sparse-memory-bind-flag-bits))
 
(defun check-display-power-state-ext (val)
  `(typep ,val (foreign-enum-type VkDisplayPowerStateEXT)))
(deftype vk-display-power-state-ext ()
  `(satisfies check-display-power-state-ext))
 
(defun check-display-plane-alpha-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkDisplayPlaneAlphaFlagBitsKHR)))
(deftype vk-display-plane-alpha-flag-bits-khr ()
  `(satisfies check-display-plane-alpha-flag-bits-khr))
 
(defun check-full-screen-exclusive-ext (val)
  `(typep ,val (foreign-enum-type VkFullScreenExclusiveEXT)))
(deftype vk-full-screen-exclusive-ext ()
  `(satisfies check-))
 
(defun check-surface-counter-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkSurfaceCounterFlagBitsEXT)))
(deftype vk-surface-counter-flag-bits-ext ()
  `(satisfies check-surface-counter-flag-bits-ext))
 
(defun check-surface-transform-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkSurfaceTransformFlagBitsKHR)))
(deftype vk-surface-transform-flag-bits-khr ()
  `(satisfies check-surface-transform-flag-bits-khr))
 
(defun check-composite-alpha-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkCompositeAlphaFlagBitsKHR)))
(deftype vk-composite-alpha-flag-bits-khr ()
  `(satisfies check-composite-alpha-flag-bits-khr))
 
(defun check-color-space-khr (val)
  `(typep ,val (foreign-enum-type VkColorSpaceKHR)))
(deftype vk-color-space-khr ()
  `(satisfies check-color-space-khr))
 
(defun check-present-mode-khr (val)
  `(typep ,val (foreign-enum-type VkPresentModeKHR)))
(deftype vk-present-mode-khr ()
  `(satisfies check-present-mode-khr))
 
(defun check-device-group-present-mode-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkDeviceGroupPresentModeFlagBitsKHR)))
(deftype vk-device-group-present-mode-flag-bits-khr ()
  `(satisfies check-device-group-present-mode-flag-bits-khr))
 
(defun check-swapchain-create-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkSwapchainCreateFlagBitsKHR)))
(deftype vk-swapchain-create-flag-bits-khr ()
  `(satisfies check-swapchain-create-flag-bits-khr))
 
(defun check-geometry-instance-flag-bits-khr (val)
  `(typep ,val (foreign-enum-type VkGeometryInstanceFlagBitsKHR)))
(deftype vk-geometry-instance-flag-bits-khr ()
  `(satisfies check-geometry-instance-flag-bits-khr))
 
(defun check-copy-acceleration-structure-mode-khr (val)
  `(typep ,val (foreign-enum-type VkCopyAccelerationStructureModeKHR)))
(deftype vk-copy-acceleration-structure-mode-khr ()
  `(satisfies check-copy-acceleration-structure-mode-khr))
 
(defun check-sample-count-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSampleCountFlagBits)))
(deftype vk-sample-count-flag-bits ()
  `(satisfies check-sample-count-flag-bits))
 
(defun check-shader-float-controls-indeopendence (val)
  `(typep ,val (foreign-enum-type VkShaderFloatControlsIndependence)))
(deftype vk-shader-float-controls-indeopendence ()
  `(satisfies check-shader-float-controls-indeopendence))
 
(defun check-subgroup-feature-flag-bits (val)
  `(typep ,val (foreign-enum-type VkSubgroupFeatureFlagBits)))
(deftype vk-subgroup-feature-flag-bits ()
  `(satisfies check-subgroup-feature-flag-bits))
 
(defun check-format (val)
  `(typep ,val (foreign-enum-type VkFormat)))
(deftype vk-format ()
  `(satisfies check-format))
 
(defun check-format-feature-flag-bits (val)
  `(typep ,val (foreign-enum-type VkFormatFeatureFlagBits)))
(deftype vk-format-feature-flag-bits ()
  `(satisfies check-format-feature-flag-bits))
 
(defun check-external-memory-feature-flag-bits-nv (val)
  `(typep ,val (foreign-enum-type VkExternalMemoryFeatureFlagBitsNV)))
(deftype vk-external-memory-feature-flag-bits-nv ()
  `(satisfies check-external-memory-feature-flag-bits-nv))
 
(defun check-external-memory-handle-type-flag-bits (val)
  `(typep ,val (foreign-enum-type VkExternalMemoryHandleTypeFlagBits)))
(deftype vk-external-memory-handle-type-flag-bits ()
  `(satisfies check-external-memory-handle-type-flag-bits))
 
(defun check-external-memory-feature-flag-bits (val)
  `(typep ,val (foreign-enum-type VkExternalMemoryFeatureFlagBits)))
(deftype vk-external-memory-feature-flag-bits ()
  `(satisfies check-external-memory-feature-flag-bits))
 
(defun check-external-semaphore-handle-type-flag-bits (val)
  `(typep ,val (foreign-enum-type VkExternalSemaphoreHandleTypeFlagBits)))
(deftype vk-external-semaphore-handle-type-flag-bits ()
  `(satisfies check-external-semaphore-handle-type-flag-bits))
 
(defun check-external-semaphore-feature-flag-bits (val)
  `(typep ,val (foreign-enum-type VkExternalSemaphoreFeatureFlagBits)))
(deftype vk-external-semaphore-feature-flag-bits ()
  `(satisfies check-external-semaphore-feature-flag-bits))
 
(defun check-external-fence-handle-type-flag-bits (val)
  `(typep ,val (foreign-enum-type VkExternalFenceHandleTypeFlagBits)))
(deftype vk-external-fence-handle-type-flag-bits ()
  `(satisfies check-external-fence-handle-type-flag-bits))
 
(defun check-external-fence-feature-flag-bits (val)
  `(typep ,val (foreign-enum-type VkExternalFenceFeatureFlagBits)))
(deftype vk-external-fence-feature-flag-bits ()
  `(satisfies check-external-fence-feature-flag-bits))
 
(defun check-object-type (val)
  `(typep ,val (foreign-enum-type VkObjectType)))
(deftype vk-object-type ()
  `(satisfies check-object-type))
 
(defun check-debug-utils-message-severity-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkDebugUtilsMessageSeverityFlagBitsEXT)))
(deftype vk-debug-utils-message-severity-flag-bits-ext ()
  `(satisfies check-debug-utils-message-severity-flag-bits-ext))
 
(defun check-debug-utils-message-type-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkDebugUtilsMessageTypeFlagBitsEXT)))
(deftype vk-debug-utils-message-type-flag-bits-ext ()
  `(satisfies check-debug-utils-message-type-flag-bits-ext))
 
(defun check-debug-report-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkDebugReportFlagBitsEXT)))
(deftype vk-debug-report-flag-bits-ext ()
  `(satisfies check-debug-report-flag-bits-ext))
 
(defun check-debug-report-object-type-ext (val)
  `(typep ,val (foreign-enum-type VkDebugReportObjectTypeEXT)))
(deftype vk-debug-report-object-type-ext ()
  `(satisfies check-debug-report-object-type-ext))
 
(defun check-tool-purpose-flag-bits-ext (val)
  `(typep ,val (foreign-enum-type VkToolPurposeFlagBitsEXT)))
(deftype vk-tool-purpose-flag-bits-ext ()
  `(satisfies check-tool-purpose-flag-bits-ext))
 
